name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1.0.0
      - name: Docker Publish
        uses: zenato/docker-action@v1.0.0
        with:
          username: rfaircloth-splunk
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: rfaircloth-splunk/splunk-connect-for-email-postfix/splunk-connect-for-email-postfix
          registry: docker.pkg.github.com
          tag: latest  
